name: Distirbuted workflow tasks

on: push

jobs:
  android_ci_job:
    name: Start Android CI workflow
    uses: ${{ github.repository }}/android/.github/workflows/ci-cd-workflow.yml@${GITHUB_REF##*/}
    secrets:
      envPAT: ${{ secrets.envPAT }}