name: Distirbuted workflow tasks

on:
  push:
  workflow_call:
    secrets:
      envPAT:
        required: false

jobs:
  android_ci_job:
    name: Start Android CI workflow
    uses: ${{ github.repository }}/android/.github/workflows/ci-cd-workflow.yml@android-ci-cd
