name: Distirbuted workflow tasks

on: push

jobs:
  android_ci_job:
    name: Start Android CI workflow
    uses: ${{github.repository_owner}}/${{github.event.repository.name}/android/.github/workflows/action.yml@${{github.sha}}
