name: Distirbuted workflow tasks

on: push

jobs:
  android_ci_job:
    name: Start Android CI workflow
    uses: hasancse91/flutter_getx_template/android/.github/workflows/ci-cd-workflow.yml@android-ci-cd
    secrets:
      envPAT: ${{ secrets.envPAT }}