name: Distirbuted workflow tasks

on:
  push:
  workflow_call:
    secrets:
      envPAT:
        required: false

jobs:
  android_ci_job:
    name: Start Android CI workflow
    uses: hasancse91/flutter_getx_template/android/.github/workflows/action.yml@android-ci-cd
