name: Distirbuted workflow tasks

on:
  push:
  workflow_call:
    secrets:
      envPAT:
        required: false

jobs:
  android_ci_job:
    name: Start Android CI workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Reuse android workflow
        uses: ./android/.github/workflows/ci-cd-workflow.yml@${GITHUB_REF##/}
